### ISSUE TITLE
500 Error when visiting webui page.

### ISSUE THREAD

**Issue by jiayev** [CoffeeVampir3/audiocraft-webui#11]
[2024-03-06 17:40:31,885] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/jiaye/anaconda3/envs/audiocraft/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jiaye/anaconda3/envs/audiocraft/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jiaye/anaconda3/envs/audiocraft/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jiaye/anaconda3/envs/audiocraft/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/jiaye/DATA/lyj/soft/stable diffusion/audiocraft-webui/webui.py", line 109, in index
    model, prompt, topp, duration, cfg_coef, topk, temperature = load_last_gen_settings()
ValueError: not enough values to unpack (expected 7, got 3)

**Comment by ryzhkin** [comment]
+1

**Comment by CoffeeVampir3** [comment]
No idea what's wrong but it falls back if that file is malformed for whatever reason now.
