### ISSUE TITLE
FileNotFoundError: Could not find module

### ISSUE THREAD

**Issue by Appolonius001** [CoffeeVampir3/audiocraft-webui#7]
```
C:\Users\Appolonius\Desktop\audiocraft-webui-main>python webui.py
Traceback (most recent call last):
  File "C:\Users\Appolonius\Desktop\audiocraft-webui-main\webui.py", line 8, in <module>
    import torch, torchaudio, pathlib
  File "C:\Users\Appolonius\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "C:\Users\Appolonius\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "C:\Users\Appolonius\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\Appolonius\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Appolonius\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Appolonius\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by Appolonius001** [comment]
ive had the original audiocraft working and running, i followed your install and i got the above error
